/**
 * Private file storage.
 *
 * Nothing here is reachable from the public tree. The storage key is derived
 * entirely from server-side values (purpose, date, uuid, detected extension),
 * so a crafted filename cannot escape the root, and every read goes through an
 * authorization check rather than an unguessable URL.
 */
import { createHash, randomUUID } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { and, eq, inArray, isNull, or } from 'drizzle-orm';
import type { DbClient } from '../db/client.ts';
import { storedFiles } from '../db/schema/core.ts';
import { animals } from '../db/schema/animals.ts';
import { vetProfessionalCases, vetProfessionalDocuments, vetVisitRequests } from '../db/schema/vets.ts';
import { inquiryMessages, listingInquiries } from '../db/schema/inquiry.ts';
import { dealDisputes, disputeEvidence } from '../db/schema/deals.ts';
import { hasMarketplaceCapability } from '../marketplace/model.ts';
import { recordAudit } from '../audit/service.ts';
import type { Actor } from '../authz/actor.ts';
import { assertCanReadFile, canReadFile, type FilePurposeName } from '../authz/policy.ts';
import { notFound, validation } from '../domain/errors.ts';
import { assertAcceptable, EXTENSION } from './signature.ts';

export interface StoredFileRecord {
  readonly id: string;
  readonly ownerAccountId: string;
  readonly purpose: FilePurposeName;
  readonly mime: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly storageKey: string;
  readonly originalName: string | null;
  readonly createdAt: Date;
}

export function storageRoot(dir: string): string {
  return path.resolve(dir);
}

/**
 * Resolve a storage key under the root and refuse anything that escapes it.
 * Keys are generated by this module, but the guard stays because a stored key
 * is still data read back from the database.
 */
export function resolveWithinRoot(root: string, storageKey: string): string {
  const absoluteRoot = storageRoot(root);
  const full = path.resolve(absoluteRoot, storageKey);
  const relative = path.relative(absoluteRoot, full);
  if (relative === '' || relative.startsWith('..') || path.isAbsolute(relative)) {
    throw validation('Unsafe storage key');
  }
  return full;
}

function newStorageKey(purpose: FilePurposeName, extension: string): string {
  const year = new Date().getUTCFullYear();
  return path.posix.join(purpose.toLowerCase(), String(year), randomUUID() + '.' + extension);
}

export interface PutFileInput {
  readonly ownerAccountId: string;
  readonly purpose: FilePurposeName;
  readonly bytes: Uint8Array;
  /** Client-supplied name, stored for display only and never used as a path. */
  readonly originalName?: string | null;
}

export async function putPrivateFile(
  tx: DbClient,
  root: string,
  actor: Actor | null,
  input: PutFileInput,
): Promise<StoredFileRecord> {
  const mime = assertAcceptable(input.purpose, input.bytes);
  const storageKey = newStorageKey(input.purpose, EXTENSION[mime]);
  const absolute = resolveWithinRoot(root, storageKey);

  await fs.mkdir(path.dirname(absolute), { recursive: true });
  // wx: never overwrite an existing object.
  await fs.writeFile(absolute, input.bytes, { flag: 'wx', mode: 0o600 });

  const sha256 = createHash('sha256').update(input.bytes).digest('hex');
  const [row] = await tx
    .insert(storedFiles)
    .values({
      ownerAccountId: input.ownerAccountId,
      purpose: input.purpose,
      mime,
      sizeBytes: input.bytes.length,
      sha256,
      storageKey,
      originalName: safeOriginalName(input.originalName),
    })
    .returning();

  const record = row! as StoredFileRecord;
  await recordAudit(tx, actor, {
    action: 'PRIVATE_FILE_STORED',
    targetType: 'STORED_FILE',
    targetId: record.id,
    // Never the bytes, never the raw name as a path — purpose, size and digest only.
    after: { purpose: record.purpose, mime: record.mime, sizeBytes: record.sizeBytes, sha256: record.sha256 },
  });
  return record;
}

export async function findFile(tx: DbClient, fileId: string): Promise<StoredFileRecord> {
  const [row] = await tx
    .select()
    .from(storedFiles)
    .where(and(eq(storedFiles.id, fileId), isNull(storedFiles.deletedAt)))
    .limit(1);
  if (!row) throw notFound('File not found');
  return row as StoredFileRecord;
}

/**
 * The one record-scoped exception to the purpose table.
 *
 * The schema is imported, not the visits service, so the file module keeps no
 * dependency on the clinical flow beyond this single question.
 */
async function vetMaySeeAnimalPhoto(
  tx: DbClient,
  actor: Actor,
  record: StoredFileRecord,
): Promise<boolean> {
  if (record.purpose !== 'ANIMAL_PHOTO' || actor.context !== 'TRUSTED_VET') return false;
  const rows = await tx
    .select({ id: vetVisitRequests.id })
    .from(vetVisitRequests)
    .innerJoin(animals, eq(animals.id, vetVisitRequests.animalId))
    .where(
      and(
        eq(animals.photoFileId, record.id),
        eq(vetVisitRequests.vetAccountId, actor.accountId),
        inArray(vetVisitRequests.status, ['CHECKED_IN', 'COMPLETED']),
      ),
    )
    .limit(1);
  return rows.length > 0;
}

/**
 * The second record-scoped exception: an attachment inside a deal thread.
 *
 * The person it was sent to is not the owner and is not a reviewer, so the
 * purpose table cannot express this — and widening the purpose would hand every
 * buyer every other thread's files. It is a question about this one file and
 * this one thread, asked here against the schema alone (PROMPT-005).
 */
async function partyMaySeeAttachment(
  tx: DbClient,
  actor: Actor,
  record: StoredFileRecord,
): Promise<boolean> {
  if (record.purpose !== 'INQUIRY_ATTACHMENT') return false;
  const rows = await tx
    .select({ id: listingInquiries.id })
    .from(inquiryMessages)
    .innerJoin(listingInquiries, eq(listingInquiries.id, inquiryMessages.inquiryId))
    .where(
      and(
        eq(inquiryMessages.fileId, record.id),
        or(
          eq(listingInquiries.buyerAccountId, actor.accountId),
          eq(listingInquiries.sellerAccountId, actor.accountId),
        ),
      ),
    )
    .limit(1);
  return rows.length > 0;
}

/**
 * The third record-scoped exception: evidence in one deposit dispute.
 *
 * The other party to the deal and the reviewer deciding that case may read it;
 * nobody else, and never a whole role across every case. Asked here against the
 * schema, for the same reason the two exceptions above are (PROMPT-006).
 */
async function partyMaySeeDisputeEvidence(
  tx: DbClient,
  actor: Actor,
  record: StoredFileRecord,
): Promise<boolean> {
  if (record.purpose !== 'DISPUTE_EVIDENCE') return false;
  const rows = await tx
    .select({
      buyerAccountId: listingInquiries.buyerAccountId,
      sellerAccountId: listingInquiries.sellerAccountId,
    })
    .from(disputeEvidence)
    .innerJoin(dealDisputes, eq(dealDisputes.id, disputeEvidence.disputeId))
    .innerJoin(listingInquiries, eq(listingInquiries.id, dealDisputes.inquiryId))
    .where(eq(disputeEvidence.fileId, record.id))
    .limit(1);
  const row = rows[0];
  if (!row) return false;
  if (row.buyerAccountId === actor.accountId || row.sellerAccountId === actor.accountId) return true;
  return hasMarketplaceCapability(actor, 'ANIMAL_DISPUTE_DECIDE');
}

/**
 * Authorized read. The permission check happens before any filesystem access,
 * so an unauthorized request cannot even probe whether the object exists.
 */
export async function readPrivateFile(
  tx: DbClient,
  root: string,
  actor: Actor,
  fileId: string,
): Promise<{ record: StoredFileRecord; bytes: Buffer }> {
  const record = await findFile(tx, fileId);
  if (!canReadFile(actor, { ownerAccountId: record.ownerAccountId, purpose: record.purpose })) {
    // One record-scoped grant: the veterinarian a visit was assigned to may see
    // that animal's photo while the visit is open at their desk (§12.5, §21.1).
    // It is a permission over one record, not over the whole purpose, so it is
    // asked as a question about this file rather than added to the policy table.
    if (
      !(await vetMaySeeAnimalPhoto(tx, actor, record)) &&
      !(await partyMaySeeAttachment(tx, actor, record)) &&
      !(await partyMaySeeDisputeEvidence(tx, actor, record))
    ) {
      assertCanReadFile(actor, { ownerAccountId: record.ownerAccountId, purpose: record.purpose });
    }
  }
  const bytes = await fs.readFile(resolveWithinRoot(root, record.storageKey));
  // Professional evidence is personal and legally meaningful: every view is recorded,
  // by whom and in which context (PHASE_2_5_SPEC_FA §10, DEC-0189).
  if (AUDITED_READS.includes(record.purpose)) {
    // A professional document also names the case it belongs to and that case's status at the moment
    // of viewing, so a review's trail shows which evidence was opened before which decision (PROMPT-007).
    const [link] =
      record.purpose === 'VET_PROFESSIONAL_DOCUMENT'
        ? await tx
            .select({ caseId: vetProfessionalDocuments.caseId, submissionVersion: vetProfessionalDocuments.submissionVersion, kind: vetProfessionalDocuments.kind, caseStatus: vetProfessionalCases.status })
            .from(vetProfessionalDocuments)
            .innerJoin(vetProfessionalCases, eq(vetProfessionalCases.id, vetProfessionalDocuments.caseId))
            .where(eq(vetProfessionalDocuments.fileId, record.id))
            .limit(1)
        : [];
    await recordAudit(tx, actor, {
      action: 'PRIVATE_FILE_READ',
      targetType: 'STORED_FILE',
      targetId: record.id,
      metadata: { purpose: record.purpose, context: actor.context, owner: actor.accountId === record.ownerAccountId, ...(link ?? {}) },
    });
  }
  return { record, bytes };
}

const AUDITED_READS: readonly string[] = ['VET_APPLICATION_DOCUMENT', 'VET_PROFESSIONAL_DOCUMENT'];

/**
 * The name a person gave a file, kept only as a label (PHASE-2.5 PROMPT-006).
 * It is never a path — the storage key is random — but it is shown back to
 * reviewers, so it loses any directory part, control characters and bidi
 * overrides that could disguise an extension, and is bounded.
 */
export function safeOriginalName(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const base = raw.split(/[\\/]/).pop() ?? '';
  const cleaned = base
    .replace(/[ -‪-‮⁦-⁩]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120);
  return cleaned === '' || cleaned === '.' || cleaned === '..' ? null : cleaned;
}

/** Soft delete: the row and its audit trail stay, the object is removed. */
export async function deletePrivateFile(
  tx: DbClient,
  root: string,
  actor: Actor,
  fileId: string,
): Promise<void> {
  const record = await findFile(tx, fileId);
  assertCanReadFile(actor, { ownerAccountId: record.ownerAccountId, purpose: record.purpose });
  await tx.update(storedFiles).set({ deletedAt: new Date() }).where(eq(storedFiles.id, fileId));
  await fs.rm(resolveWithinRoot(root, record.storageKey), { force: true });
  await recordAudit(tx, actor, {
    action: 'PRIVATE_FILE_DELETED',
    targetType: 'STORED_FILE',
    targetId: fileId,
    before: { purpose: record.purpose, sha256: record.sha256 },
  });
}
