/**
 * Private file storage.
 *
 * Nothing here is reachable from the public tree. The storage key is derived
 * entirely from server-side values (purpose, date, uuid, detected extension),
 * so a crafted filename cannot escape the root, and every read goes through an
 * authorization check rather than an unguessable URL.
 */
import { createHash, randomUUID } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { and, eq, isNull } from 'drizzle-orm';
import type { DbClient } from '../db/client.ts';
import { storedFiles } from '../db/schema/core.ts';
import { recordAudit } from '../audit/service.ts';
import type { Actor } from '../authz/actor.ts';
import { assertCanReadFile, type FilePurposeName } from '../authz/policy.ts';
import { notFound, validation } from '../domain/errors.ts';
import { assertAcceptable, EXTENSION } from './signature.ts';

export interface StoredFileRecord {
  readonly id: string;
  readonly ownerAccountId: string;
  readonly purpose: FilePurposeName;
  readonly mime: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly storageKey: string;
  readonly originalName: string | null;
  readonly createdAt: Date;
}

export function storageRoot(dir: string): string {
  return path.resolve(dir);
}

/**
 * Resolve a storage key under the root and refuse anything that escapes it.
 * Keys are generated by this module, but the guard stays because a stored key
 * is still data read back from the database.
 */
export function resolveWithinRoot(root: string, storageKey: string): string {
  const absoluteRoot = storageRoot(root);
  const full = path.resolve(absoluteRoot, storageKey);
  const relative = path.relative(absoluteRoot, full);
  if (relative === '' || relative.startsWith('..') || path.isAbsolute(relative)) {
    throw validation('Unsafe storage key');
  }
  return full;
}

function newStorageKey(purpose: FilePurposeName, extension: string): string {
  const year = new Date().getUTCFullYear();
  return path.posix.join(purpose.toLowerCase(), String(year), randomUUID() + '.' + extension);
}

export interface PutFileInput {
  readonly ownerAccountId: string;
  readonly purpose: FilePurposeName;
  readonly bytes: Uint8Array;
  /** Client-supplied name, stored for display only and never used as a path. */
  readonly originalName?: string | null;
}

export async function putPrivateFile(
  tx: DbClient,
  root: string,
  actor: Actor | null,
  input: PutFileInput,
): Promise<StoredFileRecord> {
  const mime = assertAcceptable(input.purpose, input.bytes);
  const storageKey = newStorageKey(input.purpose, EXTENSION[mime]);
  const absolute = resolveWithinRoot(root, storageKey);

  await fs.mkdir(path.dirname(absolute), { recursive: true });
  // wx: never overwrite an existing object.
  await fs.writeFile(absolute, input.bytes, { flag: 'wx', mode: 0o600 });

  const sha256 = createHash('sha256').update(input.bytes).digest('hex');
  const [row] = await tx
    .insert(storedFiles)
    .values({
      ownerAccountId: input.ownerAccountId,
      purpose: input.purpose,
      mime,
      sizeBytes: input.bytes.length,
      sha256,
      storageKey,
      originalName: input.originalName?.slice(0, 200) ?? null,
    })
    .returning();

  const record = row! as StoredFileRecord;
  await recordAudit(tx, actor, {
    action: 'PRIVATE_FILE_STORED',
    targetType: 'STORED_FILE',
    targetId: record.id,
    // Never the bytes, never the raw name as a path — purpose, size and digest only.
    after: { purpose: record.purpose, mime: record.mime, sizeBytes: record.sizeBytes, sha256: record.sha256 },
  });
  return record;
}

export async function findFile(tx: DbClient, fileId: string): Promise<StoredFileRecord> {
  const [row] = await tx
    .select()
    .from(storedFiles)
    .where(and(eq(storedFiles.id, fileId), isNull(storedFiles.deletedAt)))
    .limit(1);
  if (!row) throw notFound('File not found');
  return row as StoredFileRecord;
}

/**
 * Authorized read. The permission check happens before any filesystem access,
 * so an unauthorized request cannot even probe whether the object exists.
 */
export async function readPrivateFile(
  tx: DbClient,
  root: string,
  actor: Actor,
  fileId: string,
): Promise<{ record: StoredFileRecord; bytes: Buffer }> {
  const record = await findFile(tx, fileId);
  assertCanReadFile(actor, { ownerAccountId: record.ownerAccountId, purpose: record.purpose });
  const bytes = await fs.readFile(resolveWithinRoot(root, record.storageKey));
  return { record, bytes };
}

/** Soft delete: the row and its audit trail stay, the object is removed. */
export async function deletePrivateFile(
  tx: DbClient,
  root: string,
  actor: Actor,
  fileId: string,
): Promise<void> {
  const record = await findFile(tx, fileId);
  assertCanReadFile(actor, { ownerAccountId: record.ownerAccountId, purpose: record.purpose });
  await tx.update(storedFiles).set({ deletedAt: new Date() }).where(eq(storedFiles.id, fileId));
  await fs.rm(resolveWithinRoot(root, record.storageKey), { force: true });
  await recordAudit(tx, actor, {
    action: 'PRIVATE_FILE_DELETED',
    targetType: 'STORED_FILE',
    targetId: fileId,
    before: { purpose: record.purpose, sha256: record.sha256 },
  });
}
