/**
 * Catalogue of product settings — D15, D16, §21.4, §22, §29.2.
 *
 * `seedValue: null` means NOT_CONFIGURED and stays that way until the
 * responsible team enters the real value.
 *
 * Where a value has a starting figure, that figure is an operating default the
 * superadmin changes from `/admin/settings`, not a verified published tariff or
 * a real bank account. The note on each key says which of the two it is, and
 * every change keeps its actor, time and previous value.
 */
import type { SettingGroupName } from '../authz/policy.ts';

export type SettingKindName = 'INT' | 'MONEY_TOMAN' | 'STRING' | 'TEXT' | 'BOOL' | 'JSON';
export type SettingSourceName = 'PRODUCT_DECISION' | 'DOCUMENTED_POLICY' | 'TECHNICAL_DEFAULT' | 'OPERATIONAL_DATA';

export interface SettingDefinition {
  readonly key: string;
  readonly group: SettingGroupName;
  readonly kind: SettingKindName;
  readonly source: SettingSourceName;
  readonly labelFa: string;
  readonly noteFa?: string;
  /** null = NOT_CONFIGURED at seed time. */
  readonly seedValue: unknown;
  readonly min?: number;
  readonly max?: number;
}

export const SETTING_DEFINITIONS: readonly SettingDefinition[] = [
  // ── Deadlines ───────────────────────────────────────────────────────────
  {
    key: 'referral.validity_days',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'PRODUCT_DECISION',
    labelFa: 'مهلت اعتبار کد مراجعه (روز)',
    noteFa: 'مقدار اولیه ۲۱ روز طبق D15. هنگام صدور هر کد، مقدار فعال خوانده و روی همان کد ثبت می‌شود.',
    seedValue: 21,
    min: 1,
    max: 365,
  },

  // ── Tariffs ─────────────────────────────────────────────────────────────
  {
    key: 'fee.membership_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'PRODUCT_DECISION',
    labelFa: 'هزینه عضویت انجمن',
    noteFa: 'مبلغ مبنای مستند ۳۰۰٬۰۰۰ تومان. عضویت مادام‌العمر است و تمدید ندارد (D04).',
    seedValue: '300000',
  },
  {
    key: 'fee.registration_sheet_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'هزینه صدور برگه ثبتی (هر حیوان)',
    noteFa:
      'مقدار شروع عملیاتی است و تعرفه رسمی اعلام‌شده انجمن نیست؛ سوپرادمین آن را از /admin/settings تغییر می‌دهد و مبلغ هر پرداخت در همان لحظه منجمد می‌شود.',
    seedValue: '250000',
  },
  {
    key: 'fee.pedigree_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'هزینه صدور شجره‌نامه',
    noteFa:
      'مقدار شروع عملیاتی است و تعرفه رسمی اعلام‌شده انجمن نیست؛ سوپرادمین آن را از /admin/settings تغییر می‌دهد و مبلغ هر پرداخت در همان لحظه منجمد می‌شود.',
    seedValue: '400000',
  },
  {
    key: 'fee.mating_permit_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'هزینه مجوز جفت‌گیری',
    noteFa:
      'مقدار شروع عملیاتی است و تعرفه رسمی اعلام‌شده انجمن نیست؛ سوپرادمین آن را از /admin/settings تغییر می‌دهد و مبلغ هر پرداخت در همان لحظه منجمد می‌شود.',
    seedValue: '300000',
  },
  {
    key: 'fee.kennel_registration_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'هزینه ثبت کنل',
    noteFa:
      'مقدار شروع عملیاتی است و تعرفه رسمی اعلام‌شده انجمن نیست؛ سوپرادمین آن را از /admin/settings تغییر می‌دهد و مبلغ هر پرداخت در همان لحظه منجمد می‌شود.',
    seedValue: '150000',
  },
  {
    key: 'fee.puppy_card_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'هزینه صدور کارت هر توله',
    noteFa:
      'مقدار شروع عملیاتی است و تعرفه رسمی اعلام‌شده انجمن نیست؛ سوپرادمین آن را از /admin/settings تغییر می‌دهد و مبلغ هر پرداخت در همان لحظه منجمد می‌شود.',
    seedValue: '120000',
  },

  // ── Genetics centre (single fixed centre, D07) ───────────────────────────
  {
    key: 'genetics_centre.name',
    group: 'GENETICS_CENTRE',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نام مرکز ژنتیک',
    noteFa: 'یک مرکز ثابت؛ هیچ Selector مرکزی وجود ندارد (D07).',
    seedValue: 'مرکز ژنتیک هم‌زیست',
  },
  {
    key: 'genetics_centre.contact_phone',
    group: 'GENETICS_CENTRE',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'شماره تماس مرکز ژنتیک',
    seedValue: '02100000000',
  },
  {
    key: 'genetics_centre.address',
    group: 'GENETICS_CENTRE',
    kind: 'TEXT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نشانی مرکز ژنتیک',
    seedValue: 'تهران — نشانی مرکز ژنتیک، از پنل مدیریت تکمیل شود',
  },
  {
    key: 'genetics_centre.payment_account',
    group: 'GENETICS_CENTRE',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'شماره حساب اعلام‌شده مرکز ژنتیک',
    noteFa: 'مقدار شروع عملیاتی است و باید پیش از اعلام به کاربران با شماره حساب واقعی مرکز جایگزین شود.',
    seedValue: 'IR000000000000000000000000',
  },
  {
    key: 'genetics_centre.payment_card',
    group: 'GENETICS_CENTRE',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'شماره کارت اعلام‌شده مرکز ژنتیک',
    noteFa:
      'داده مالی واقعی. هیچ شماره نمونه یا ساختگی وارد نمی‌شود؛ شماره حساب برای اعلام کافی است و کارت اختیاری می‌ماند.',
    seedValue: null,
  },
  {
    key: 'genetics_centre.test_fee_toman',
    group: 'GENETICS_CENTRE',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'هزینه آزمایش مرکز ژنتیک',
    noteFa: 'پرداخت مستقیم به مرکز با فیش؛ از Checkout همزیست جداست (§۲۲).',
    seedValue: '1500000',
  },

  // ── Breeding policy (read-only product rule, §17.2) ──────────────────────
  {
    key: 'cooldown.male_days',
    group: 'BREEDING_POLICY',
    kind: 'INT',
    source: 'DOCUMENTED_POLICY',
    labelFa: 'بازه هشدار جفت‌گیری نر (روز)',
    noteFa: 'قاعده مستند محصول: ۱۴ روز از آخرین تاریخ تأییدشده دوطرفه. هشدار است، نه قفل.',
    seedValue: 14,
  },
  {
    key: 'cooldown.female_months',
    group: 'BREEDING_POLICY',
    kind: 'INT',
    source: 'DOCUMENTED_POLICY',
    labelFa: 'بازه هشدار جفت‌گیری ماده (ماه تقویمی)',
    noteFa: 'قاعده مستند محصول: شش ماه تقویمی با clamp پایان ماه (DEC-0005). به روز تبدیل نمی‌شود.',
    seedValue: 6,
  },

  // ── OTP technical defaults (DEC-0006) ───────────────────────────────────
  {
    key: 'otp.ttl_seconds',
    group: 'OTP_TECHNICAL',
    kind: 'INT',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'طول عمر کد یک‌بارمصرف (ثانیه)',
    noteFa: 'پیش‌فرض فنی قابل تغییر (DEC-0006)، نه سیاست تأییدشده مالک محصول.',
    seedValue: 120,
    min: 30,
    max: 900,
  },
  {
    key: 'otp.resend_interval_seconds',
    group: 'OTP_TECHNICAL',
    kind: 'INT',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'فاصله مجاز ارسال مجدد کد (ثانیه)',
    seedValue: 60,
    min: 15,
    max: 600,
  },
  {
    key: 'otp.max_attempts',
    group: 'OTP_TECHNICAL',
    kind: 'INT',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'سقف تلاش نادرست کد',
    seedValue: 5,
    min: 3,
    max: 20,
  },
  {
    key: 'otp.max_sends_per_hour',
    group: 'OTP_TECHNICAL',
    kind: 'INT',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'سقف ارسال کد برای هر شماره در ساعت',
    noteFa: 'سد بالادستی در برابر سوءاستفاده از ارسال پیامک؛ پیش‌فرض فنی (DEC-0026).',
    seedValue: 5,
    min: 1,
    max: 60,
  },
  {
    key: 'session.ttl_days',
    group: 'OTP_TECHNICAL',
    kind: 'INT',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'طول عمر نشست ورود (روز)',
    noteFa: 'پیش‌فرض فنی قابل تغییر (DEC-0026)، نه سیاست تأییدشده مالک محصول.',
    seedValue: 30,
    min: 1,
    max: 365,
  },
  {
    key: 'otp.lock_minutes',
    group: 'OTP_TECHNICAL',
    kind: 'INT',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'مدت قفل پس از تلاش‌های نادرست (دقیقه)',
    seedValue: 15,
    min: 1,
    max: 1440,
  },

  // ── Integrations (§21.4: configurable operational data, not a code change) ──
  {
    key: 'integration.sms.mode',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'حالت آداپتور پیامک',
    noteFa:
      'MOCK_AUTO یعنی ارسال شبیه‌سازی‌شده و همیشه موفق؛ کد در صندوق توسعه ثبت می‌شود و به شماره واقعی چیزی نمی‌رود. PROVIDER یعنی سرویس‌دهنده واقعی که نام و کلید آن باید وارد شود.',
    seedValue: 'MOCK_AUTO',
  },
  {
    key: 'integration.sms.provider',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نام سرویس‌دهنده پیامک',
    noteFa: 'فقط وقتی حالت PROVIDER است معنا دارد.',
    seedValue: null,
  },
  {
    key: 'integration.sms.api_key',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'کلید سرویس پیامک',
    noteFa: 'در لاگ و Audit ثبت نمی‌شود.',
    seedValue: null,
  },
  {
    key: 'integration.payment.mode',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'حالت درگاه پرداخت',
    noteFa:
      'MOCK_AUTO یعنی پرداخت شبیه‌سازی‌شده که بدون دخالت کاربر موفق تأیید می‌شود. DEV_GATEWAY همان درگاه توسعه با صفحه پرداخت است. PROVIDER یعنی درگاه واقعی. تأیید همیشه سمت سرور انجام می‌شود.',
    seedValue: 'MOCK_AUTO',
  },
  {
    key: 'integration.payment.provider',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نام درگاه پرداخت',
    noteFa: 'فقط وقتی حالت PROVIDER است معنا دارد.',
    seedValue: null,
  },
  {
    key: 'integration.payment.api_key',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'کلید درگاه پرداخت',
    noteFa: 'در لاگ و Audit ثبت نمی‌شود.',
    seedValue: null,
  },
  {
    key: 'integration.map.provider',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'سرویس نقشه',
    noteFa: 'مقدار فعلی «neshan» است. نبود کلید، ثبت نشانی دستی را قفل نمی‌کند.',
    seedValue: 'neshan',
  },
  {
    key: 'integration.map.api_key',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'کلید سرویس نقشه (نشان)',
    noteFa:
      'کلید وب‌سرویس نشان از پنل نشان گرفته می‌شود. تا واردنشدن، نقشه نمایش داده نمی‌شود و ورود دستی نشانی سر جای خود می‌ماند.',
    seedValue: null,
  },
  {
    key: 'integration.map.embed_url_template',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'الگوی نشانی نقشه جاسازی‌شده',
    noteFa:
      'نشانی embed سرویس نقشه با جای‌گذارهای {lat}، {lng} و {key}. تا واردنشدن، نقشه‌ای نمایش داده نمی‌شود؛ قالب نشانی حدس زده نمی‌شود و باید از مستندات همان سرویس گرفته شود (DEC-0175).',
    seedValue: null,
  },
  {
    key: 'integration.document_render.engine',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'موتور تولید PDF سند',
    noteFa:
      'CHROMIUM یعنی تولید PDF با همان موتور Chromium نصب‌شده در همین پروژه؛ رایگان، بدون سرویس بیرونی و سازگار با متن فارسی و راست‌به‌چپ. NONE یعنی خروجی PDF ساخته نمی‌شود.',
    seedValue: 'CHROMIUM',
  },
  {
    key: 'integration.chip_reader.mode',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'روش ورود شماره میکروچیپ',
    noteFa:
      'KEYBOARD_WEDGE یعنی ریدر بلوتوثی مثل صفحه‌کلید عمل می‌کند و شماره را در همان فیلد تایپ می‌کند؛ هیچ یکپارچه‌سازی سخت‌افزاری لازم نیست و ورود دستی همیشه در دسترس است.',
    seedValue: 'KEYBOARD_WEDGE',
  },

  // ── Guide text ──────────────────────────────────────────────────────────
  {
    key: 'guide_text.vet_pricing_notice',
    group: 'GUIDE_TEXT',
    kind: 'TEXT',
    source: 'PRODUCT_DECISION',
    labelFa: 'متن اطلاع هزینه در Finder',
    noteFa: 'متن مصوب §۱۱.۱.',
    seedValue: 'برای اطلاع دقیق از قیمت‌ها با دامپزشک یا مرکز تماس بگیرید.',
  },
  {
    key: 'guide_text.registration_sheet_notice',
    group: 'GUIDE_TEXT',
    kind: 'TEXT',
    source: 'PRODUCT_DECISION',
    labelFa: 'متن برگه ثبتی درباره نتیجه ژنتیک',
    noteFa: 'متن مصوب §۱۳.',
    seedValue: 'نمونه خون دریافت شده؛ آزمایش Parentage هنوز انجام نشده است.',
  },
  {
    key: 'guide_text.postal_request_notice',
    group: 'GUIDE_TEXT',
    kind: 'TEXT',
    source: 'PRODUCT_DECISION',
    labelFa: 'متن محدوده ارسال پستی',
    noteFa: 'D17: فاز اول فقط ثبت درخواست است.',
    seedValue: 'در این مرحله فقط درخواست ارسال ثبت می‌شود؛ ثبت درخواست به معنی ارسال واقعی سند نیست.',
  },
  // ── Moderation (Phase 2) ───────────────────────────────────────────────
  {
    key: 'moderation.report_daily_limit',
    group: 'MODERATION',
    kind: 'INT',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'سقف گزارش هر حساب در ۲۴ ساعت',
    noteFa: 'سد فنی در برابر گزارش انبوه (DEC-0161)؛ پیش‌فرض قابل تغییر، نه سیاست تأییدشده مالک محصول.',
    seedValue: 10,
    min: 1,
    max: 100,
  },
  {
    key: 'verification.attempt_hourly_limit',
    group: 'MODERATION',
    kind: 'INT',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'سقف استعلام اصالت از یک نشانی در ساعت',
    noteFa: 'سد فنی در برابر حدس‌زدن کد سند (§۱۷)؛ پیش‌فرض قابل تغییر، نه سیاست تأییدشده مالک محصول.',
    seedValue: 30,
    min: 1,
    max: 1000,
  },
  {
    key: 'moderation.suggestion_daily_limit',
    group: 'MODERATION',
    kind: 'INT',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'سقف پیشنهاد ثبت دامپزشک یا مرکز در ۲۴ ساعت',
    noteFa: 'سد فنی در برابر پیشنهاد انبوه (DEC-0169)؛ پیش‌فرض قابل تغییر، نه سیاست تأییدشده مالک محصول.',
    seedValue: 5,
    min: 1,
    max: 50,
  },

  // ── Advertising packages (Phase 2, §14, P2-D03) ────────────────────────
  // Every price starts NOT_CONFIGURED on purpose: no package tariff has been
  // supplied, and an unpriced plan may not be sold rather than being sold for
  // nothing. The superadmin enters the real figures in /admin/settings.
  {
    key: 'advertising.featured_30_toman',
    group: 'ADVERTISING',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'قیمت بسته ویژه ۳۰ روزه',
    noteFa: 'تا ثبت مبلغ واقعی، این بسته قابل خرید نیست (§۱۴).',
    seedValue: null,
  },
  {
    key: 'advertising.featured_90_toman',
    group: 'ADVERTISING',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'قیمت بسته ویژه ۹۰ روزه',
    noteFa: 'تا ثبت مبلغ واقعی، این بسته قابل خرید نیست (§۱۴).',
    seedValue: null,
  },
  {
    key: 'advertising.featured_365_toman',
    group: 'ADVERTISING',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'قیمت بسته ویژه ۳۶۵ روزه',
    noteFa: 'تا ثبت مبلغ واقعی، این بسته قابل خرید نیست (§۱۴).',
    seedValue: null,
  },
  {
    key: 'advertising.pro_30_toman',
    group: 'ADVERTISING',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'قیمت بسته حرفه‌ای ۳۰ روزه',
    noteFa: 'تا ثبت مبلغ واقعی، این بسته قابل خرید نیست (§۱۴).',
    seedValue: null,
  },
  {
    key: 'advertising.pro_90_toman',
    group: 'ADVERTISING',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'قیمت بسته حرفه‌ای ۹۰ روزه',
    noteFa: 'تا ثبت مبلغ واقعی، این بسته قابل خرید نیست (§۱۴).',
    seedValue: null,
  },
  {
    key: 'advertising.pro_365_toman',
    group: 'ADVERTISING',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'قیمت بسته حرفه‌ای ۳۶۵ روزه',
    noteFa: 'تا ثبت مبلغ واقعی، این بسته قابل خرید نیست (§۱۴).',
    seedValue: null,
  },
  // ── Veterinary practice licence period (Phase 2.5, PROMPT-008) ──────────
  // Nothing here has a starting figure: no tariff, period length, reminder
  // window or grace rule has been supplied for this product. Until the real
  // values are entered in /admin/settings, activation and renewal stay closed
  // rather than being sold for nothing or given an invented duration.
  {
    key: 'vet_licence.activation_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'تعرفه فعال‌سازی پروانه فعالیت دامپزشک',
    noteFa: 'تا ثبت مبلغ واقعی، فعال‌سازی پروانه باز نمی‌شود. مبلغ در لحظه شروع پرداخت روی همان دوره ثبت می‌شود.',
    seedValue: null,
  },
  {
    key: 'vet_licence.renewal_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'تعرفه تمدید پروانه فعالیت دامپزشک',
    noteFa: 'تا ثبت مبلغ واقعی، تمدید باز نمی‌شود. مبلغ در لحظه شروع پرداخت روی همان دوره ثبت می‌شود.',
    seedValue: null,
  },
  {
    key: 'vet_licence.period_days',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'طول دوره فعالیت پروانه (روز)',
    noteFa: 'طول دوره‌ای که یک پرداخت تأییدشده می‌خرد. مقدار واقعی اعلام نشده است؛ تا ثبت آن، فعال‌سازی و تمدید باز نمی‌شود.',
    seedValue: null,
    min: 1,
    max: 3650,
  },
  {
    key: 'vet_licence.reminder_days_before',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'یادآوری پیش از پایان دوره (روز)',
    noteFa: 'چند روز مانده به پایان دوره، یادآوری تمدید برای دامپزشک ساخته شود. تا ثبت مقدار، هیچ یادآوری ساخته نمی‌شود.',
    seedValue: null,
    min: 1,
    max: 365,
  },
  {
    key: 'vet_licence.grace_days',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مهلت ارفاقی پس از پایان دوره (روز)',
    noteFa: 'چند روز پس از پایان دوره، Tag دارای پروانه پیش از تنزل نگه داشته شود. تا ثبت مقدار، مهلت ارفاقی وجود ندارد و تنزل دقیقاً در پایان دوره است.',
    seedValue: null,
    min: 0,
    max: 365,
  },
  // ── Timed association membership (Phase 2.5, PROMPT-009) ───────────────
  // The first period is charged at the existing `fee.membership_toman`. None of
  // the figures below has a starting value: no duration, reminder window or
  // grace rule has been supplied for a timed membership, and until they are
  // entered a membership period cannot be sold or given an invented length.
  {
    key: 'membership.renewal_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'تعرفه تمدید عضویت انجمن',
    noteFa: 'تا ثبت مبلغ واقعی، تمدید عضویت باز نمی‌شود. مبلغ در لحظه شروع پرداخت روی همان دوره ثبت می‌شود.',
    seedValue: null,
  },
  {
    key: 'membership.period_days',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'طول دوره عضویت انجمن (روز)',
    noteFa: 'طول دوره‌ای که یک پرداخت تأییدشده عضویت می‌خرد. مقدار واقعی اعلام نشده است؛ تا ثبت آن، پرداخت عضویت باز نمی‌شود.',
    seedValue: null,
    min: 1,
    max: 3650,
  },
  {
    key: 'membership.reminder_days_before',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'یادآوری پیش از پایان عضویت (روز)',
    noteFa: 'چند روز مانده به پایان دوره، یادآوری تمدید ساخته شود. تا ثبت مقدار، هیچ یادآوری ساخته نمی‌شود.',
    seedValue: null,
    min: 1,
    max: 365,
  },
  {
    key: 'membership.grace_days',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مهلت ارفاقی پس از پایان عضویت (روز)',
    noteFa: 'چند روز پس از پایان دوره، عضویت پیش از منقضی شدن معتبر بماند. تا ثبت مقدار، مهلت ارفاقی وجود ندارد.',
    seedValue: null,
    min: 0,
    max: 365,
  },
  // ── Trusted veterinarian (Phase 2.5, PROMPT-010) ───────────────────────
  // The terms a trusted applicant accepts are a document the association writes,
  // and the version they accepted is stored with their application. No text and
  // no version is invented here: until both are entered, the application path
  // stays closed rather than asking somebody to accept an empty undertaking.
  {
    key: 'guide_text.trusted_vet_terms',
    group: 'GUIDE_TEXT',
    kind: 'TEXT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'متن تعهدنامه دامپزشک معتمد',
    noteFa: 'متنی که متقاضی معتمد می‌پذیرد. تا ثبت متن واقعی، درخواست معتمد باز نمی‌شود.',
    seedValue: null,
  },
  {
    key: 'trusted_vet.terms_version',
    group: 'GUIDE_TEXT',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نسخه تعهدنامه دامپزشک معتمد',
    noteFa: 'هر بار که متن تعهدنامه عوض می‌شود، این نسخه هم باید عوض شود. نسخه پذیرفته‌شده روی همان درخواست ثبت می‌ماند.',
    seedValue: null,
  },
  {
    key: 'trusted_vet.declaration_version',
    group: 'GUIDE_TEXT',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نسخه متن خوداظهاری تجهیزات',
    noteFa: 'نسخه عبارتی که متقاضی با آن داشتن میکروچیپ‌ریدر را خوداظهاری می‌کند. مدرکی لازم نیست؛ همه‌جا «تجهیزات اعلام‌شده» نوشته می‌شود.',
    seedValue: null,
  },
  // ── Trusted veterinarian period (Phase 2.5, PROMPT-011) ────────────────
  // As with the licence period, nothing here has a starting figure: no tariff,
  // duration, reminder window or grace rule has been supplied for the trusted
  // standing, so until they are entered it cannot be sold or given a length.
  {
    key: 'trusted_vet.activation_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'تعرفه فعال‌سازی دوره دامپزشک معتمد',
    noteFa: 'تا ثبت مبلغ واقعی، پرداخت دوره معتمد باز نمی‌شود. مبلغ در لحظه شروع پرداخت روی همان دوره ثبت می‌شود.',
    seedValue: null,
  },
  {
    key: 'trusted_vet.renewal_toman',
    group: 'FEES',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'تعرفه تمدید دوره دامپزشک معتمد',
    noteFa: 'تا ثبت مبلغ واقعی، تمدید معتمد باز نمی‌شود.',
    seedValue: null,
  },
  {
    key: 'trusted_vet.period_days',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'طول دوره دامپزشک معتمد (روز)',
    noteFa: 'طول دوره‌ای که یک پرداخت تأییدشده معتمد می‌خرد. مقدار واقعی اعلام نشده است.',
    seedValue: null,
    min: 1,
    max: 3650,
  },
  {
    key: 'trusted_vet.reminder_days_before',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'یادآوری پیش از پایان دوره معتمد (روز)',
    noteFa: 'تا ثبت مقدار، هیچ یادآوری تمدید معتمد ساخته نمی‌شود.',
    seedValue: null,
    min: 1,
    max: 365,
  },
  {
    key: 'trusted_vet.grace_days',
    group: 'DEADLINES',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مهلت ارفاقی پس از پایان دوره معتمد (روز)',
    noteFa: 'تا ثبت مقدار، مهلت ارفاقی وجود ندارد و دسترسی معتمد دقیقاً در پایان دوره برداشته می‌شود.',
    seedValue: null,
    min: 0,
    max: 365,
  },
  // ── Public pages (Phase 2.5, PROMPT-014) ──────────────────────────────
  // Everything a visitor is told about how to reach Hamzist, and the two texts
  // the association owns. Not one of them has a starting value: a phone number,
  // an address or a set of regulations nobody supplied is a fabricated fact, so
  // until they are entered the public page says plainly that they are not
  // registered yet rather than showing an invented one.
  {
    key: 'contact.email',
    group: 'GUIDE_TEXT',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نشانی ایمیل تماس همزیست',
    noteFa: 'در صفحه «تماس با ما» نمایش داده می‌شود. تا ثبت نشانی واقعی، صفحه می‌گوید که ثبت نشده است.',
    seedValue: null,
  },
  {
    key: 'contact.phone',
    group: 'GUIDE_TEXT',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'شماره تماس همزیست',
    noteFa: 'در صفحه «تماس با ما» نمایش داده می‌شود؛ شماره ساختگی نوشته نمی‌شود.',
    seedValue: null,
  },
  {
    key: 'contact.address_fa',
    group: 'GUIDE_TEXT',
    kind: 'TEXT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نشانی پستی همزیست',
    noteFa: 'نشانی‌ای که مکاتبه رسمی به آن فرستاده می‌شود.',
    seedValue: null,
  },
  {
    key: 'contact.hours_fa',
    group: 'GUIDE_TEXT',
    kind: 'TEXT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'ساعت پاسخ‌گویی',
    noteFa: 'ساعت‌هایی که تماس پاسخ داده می‌شود. تا ثبت، چیزی وعده داده نمی‌شود.',
    seedValue: null,
  },
  {
    key: 'guide_text.association_membership_terms',
    group: 'GUIDE_TEXT',
    kind: 'TEXT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'شرایط عضویت انجمن (متن عمومی)',
    noteFa: 'متنی که در صفحه عمومی «شرایط عضویت انجمن» خوانده می‌شود. مبلغ در این متن نوشته نمی‌شود؛ تعرفه فقط در لحظه پرداخت دیده می‌شود.',
    seedValue: null,
  },
  {
    key: 'guide_text.association_regulations',
    group: 'GUIDE_TEXT',
    kind: 'TEXT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مقررات انجمن (متن عمومی)',
    noteFa: 'مقرراتی که انجمن منتشر می‌کند. تا ثبت متن واقعی، صفحه خالی نمی‌ماند بلکه می‌گوید هنوز منتشر نشده است.',
    seedValue: null,
  },
  // ── Notification channel policy (Phase 2.5, PROMPT-015) ───────────────
  // Whether a message may leave the product, and how hard the outbox tries.
  // SMS starts OFF: no real provider is configured, and a channel that silently
  // fails is worse than one that is honestly closed. The wording itself lives in
  // the versioned template catalogue, not here, so a sentence that reaches
  // somebody's phone is reviewed as a whole rather than typed into a settings box.
  {
    key: 'notifications.sms_enabled',
    group: 'INTEGRATIONS',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'ارسال پیامک اعلان‌ها',
    noteFa: 'مقدار ON یا OFF. تا وقتی OFF است، اعلان‌ها فقط در خود سامانه ثبت می‌شوند و هیچ پیامکی صف نمی‌شود.',
    seedValue: 'OFF',
  },
  {
    key: 'notifications.sms_max_attempts',
    group: 'INTEGRATIONS',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'حداکثر تلاش ارسال پیامک',
    noteFa: 'هر پیامک ناموفق تا این تعداد با فاصله فزاینده دوباره تلاش می‌شود و پس از آن ناموفق ثبت می‌ماند.',
    seedValue: 5,
  },
  {
    key: 'notifications.sms_retry_seconds',
    group: 'INTEGRATIONS',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'فاصله نخستین تلاش دوباره (ثانیه)',
    noteFa: 'فاصله تلاش‌های بعدی از این عدد شروع می‌شود و هر بار دو برابر می‌شود.',
    seedValue: 60,
  },

  // ── Phase 3: animal marketplace (PROMPT-002, DEC-0204) ────────────────
  //
  // Two of these carry a real starting number because PRODUCT_DECISIONS states
  // it outright: the eight-week minimum handover age (§3) and the three
  // mandatory photos (§3). Everything else — durations, limits, publication
  // fees, the commission formula, the payment window and the penalties — is a
  // figure somebody with the authority to set a tariff has to enter. None of
  // them is guessed here, and each one keeps its flow closed until it is set.
  {
    key: 'market.animal.min_handover_age_days',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'PRODUCT_DECISION',
    labelFa: 'حداقل سن تحویل توله (روز)',
    noteFa:
      'مقدار اولیه ۵۶ روز (۸ هفته) طبق تصمیم محصول. آگهی می‌تواند زودتر منتشر شود، اما تحویل و انتقال مالکیت تا این سن بسته است. تغییر این عدد روی معامله‌های در جریان اثر ندارد؛ هر معامله مقدار لحظه خودش را نگه می‌دارد.',
    seedValue: 56,
    min: 1,
    max: 365,
  },
  {
    key: 'market.animal.min_listing_photos',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'PRODUCT_DECISION',
    labelFa: 'حداقل تعداد تصویر آگهی',
    noteFa: 'مقدار اولیه ۳ تصویر واقعی طبق تصمیم محصول. ویدئو اختیاری است و در این شمارش نمی‌آید.',
    seedValue: 3,
    min: 1,
    max: 20,
  },
  {
    key: 'market.animal.listing_duration_days',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مدت اعتبار آگهی حیوان (روز)',
    noteFa: 'تا ثبت این عدد، انتشار آگهی باز نمی‌شود؛ آگهی بدون تاریخ انقضا منتشر نمی‌شود.',
    seedValue: null,
    min: 1,
    max: 365,
  },
  {
    key: 'market.animal.listing_renewal_days',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مدت تمدید آگهی حیوان (روز)',
    noteFa: 'هر تمدید این تعداد روز به اعتبار آگهی اضافه می‌کند.',
    seedValue: null,
    min: 1,
    max: 365,
  },
  {
    key: 'market.animal.max_active_listings_owner',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'حداکثر آگهی فعال هر مالک',
    noteFa: 'سقف آگهی هم‌زمان برای مالک عادی. جدا از سقف کنل نگه داشته می‌شود.',
    seedValue: null,
    min: 1,
    max: 1000,
  },
  {
    key: 'market.animal.max_active_listings_kennel',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'حداکثر آگهی فعال هر کنل',
    noteFa: 'سقف آگهی هم‌زمان برای کنل تأییدشده.',
    seedValue: null,
    min: 1,
    max: 1000,
  },
  {
    key: 'market.animal.listing_publication_fee_toman',
    group: 'ANIMAL_MARKET',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'هزینه انتشار آگهی حیوان',
    noteFa: 'تا ثبت مبلغ، مسیر پرداخت انتشار باز نمی‌شود. خالی بودن یعنی «تعیین‌نشده»، نه رایگان.',
    seedValue: null,
  },
  {
    key: 'market.animal.listing_renewal_fee_toman',
    group: 'ANIMAL_MARKET',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'هزینه تمدید آگهی حیوان',
    noteFa: 'تا ثبت مبلغ، تمدید باز نمی‌شود. خالی بودن یعنی «تعیین‌نشده»، نه رایگان.',
    seedValue: null,
  },
  {
    key: 'market.animal.commission_fixed_toman',
    group: 'ANIMAL_MARKET',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'بخش ثابت کارمزد فروش حیوان',
    noteFa:
      'کارمزد = این مبلغ ثابت + درصدی از قیمت نهایی. بیعانه دقیقاً برابر همین کارمزد است و در لحظه قفل قیمت نهایی منجمد می‌شود؛ تغییر بعدی این مقدار معامله‌های ثبت‌شده را بازنویسی نمی‌کند.',
    seedValue: null,
  },
  {
    key: 'market.animal.commission_percent_bp',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'بخش درصدی کارمزد فروش حیوان (در ده‌هزار)',
    noteFa:
      'برای پرهیز از اعشار، درصد در واحد basis point ثبت می‌شود: ۱۰۰ یعنی ۱٪ و ۱۰۰۰۰ یعنی ۱۰۰٪. محاسبه فقط پس از قفل قیمت نهایی انجام می‌شود.',
    seedValue: null,
    min: 0,
    max: 10000,
  },
  {
    key: 'market.animal.commission_min_toman',
    group: 'ANIMAL_MARKET',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'کف کارمزد فروش حیوان',
    noteFa: 'اگر فرمول عددی کمتر از این بدهد، همین مقدار اعمال می‌شود.',
    seedValue: null,
  },
  {
    key: 'market.animal.commission_max_toman',
    group: 'ANIMAL_MARKET',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'سقف کارمزد فروش حیوان',
    noteFa: 'اگر فرمول عددی بیشتر از این بدهد، همین مقدار اعمال می‌شود.',
    seedValue: null,
  },
  {
    key: 'market.animal.request_payment_window_hours',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مهلت پرداخت بیعانه پس از پذیرش (ساعت)',
    noteFa: 'پس از انقضای این مهلت رزرو آزاد و سایر درخواست‌ها دوباره باز می‌شوند.',
    seedValue: null,
    min: 1,
    max: 720,
  },
  {
    key: 'market.animal.cancellation_policy_version',
    group: 'ANIMAL_MARKET',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نسخه سیاست لغو و استرداد حیوان',
    noteFa:
      'شناسه نسخه سیاستی که هر معامله در لحظه رزرو به آن گره می‌خورد. بدون نسخه ثبت‌شده، بیعانه دریافت نمی‌شود، چون معلوم نیست طرفین با چه شرایطی موافقت کرده‌اند.',
    seedValue: null,
  },
  {
    key: 'market.animal.buyer_cancellation_penalty_bp',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'جریمه انصراف خریدار پس از پذیرش (در ده‌هزار از بیعانه)',
    noteFa: 'پیش از پذیرش فروشنده استرداد کامل است و این عدد اصلاً اعمال نمی‌شود.',
    seedValue: null,
    min: 0,
    max: 10000,
  },
  {
    key: 'market.animal.seller_cancellation_penalty_toman',
    group: 'ANIMAL_MARKET',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'جریمه انصراف فروشنده',
    noteFa: 'انصراف فروشنده استرداد کامل به خریدار دارد؛ این مبلغ جریمه‌ای است که برای فروشنده ثبت می‌شود.',
    seedValue: null,
  },
  {
    key: 'market.animal.seller_cancellation_restriction_days',
    group: 'ANIMAL_MARKET',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'محدودیت فروشنده پس از انصراف (روز)',
    noteFa: 'محدودیت تصاعدی است؛ این عدد پایه دوره است و تکرار انصراف آن را چند برابر می‌کند.',
    seedValue: null,
    min: 1,
    max: 3650,
  },
  {
    key: 'market.animal.promotion_7_toman',
    group: 'ANIMAL_MARKET',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'بسته تبلیغ آگهی حیوان — ۷ روز',
    noteFa: 'تبلیغ بالاتر از نتایج طبیعی و با برچسب روشن دیده می‌شود و روی امتیاز و رتبه طبیعی اثر ندارد.',
    seedValue: null,
  },
  {
    key: 'market.animal.promotion_30_toman',
    group: 'ANIMAL_MARKET',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'بسته تبلیغ آگهی حیوان — ۳۰ روز',
    noteFa: 'تبلیغ بالاتر از نتایج طبیعی و با برچسب روشن دیده می‌شود و روی امتیاز و رتبه طبیعی اثر ندارد.',
    seedValue: null,
  },

  // ── Phase 3: merchandise commerce (PROMPT-002, DEC-0204) ──────────────
  {
    key: 'market.shop.commission_percent_bp',
    group: 'COMMERCE',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'کمیسیون فروشگاه (در ده‌هزار)',
    noteFa: 'در واحد basis point: ۱۰۰ یعنی ۱٪. مبلغ کمیسیون هر قلم در لحظه پرداخت منجمد می‌شود.',
    seedValue: null,
    min: 0,
    max: 10000,
  },
  {
    key: 'market.shop.commission_min_toman',
    group: 'COMMERCE',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'کف کمیسیون هر زیرسفارش',
    noteFa: 'اگر کمیسیون محاسبه‌شده کمتر از این باشد، همین مقدار برداشت می‌شود.',
    seedValue: null,
  },
  {
    key: 'market.shop.seller_plan_basic_monthly_toman',
    group: 'COMMERCE',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'اشتراک ماهانه فروشنده — پلن پایه',
    noteFa: 'تا ثبت مبلغ، این پلن قابل خرید نیست.',
    seedValue: null,
  },
  {
    key: 'market.shop.seller_plan_pro_monthly_toman',
    group: 'COMMERCE',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'اشتراک ماهانه فروشنده — پلن حرفه‌ای',
    noteFa: 'تا ثبت مبلغ، این پلن قابل خرید نیست.',
    seedValue: null,
  },
  {
    key: 'market.shop.suborder_acceptance_window_hours',
    group: 'COMMERCE',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مهلت پذیرش زیرسفارش توسط فروشنده (ساعت)',
    noteFa: 'عدم پذیرش در این مهلت باعث لغو و بازپرداخت خودکار همان زیرسفارش می‌شود؛ بقیه سفارش دست‌نخورده می‌ماند.',
    seedValue: null,
    min: 1,
    max: 720,
  },
  {
    key: 'market.shop.return_window_days',
    group: 'COMMERCE',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مهلت مرجوعی پس از تحویل (روز)',
    noteFa: 'سیاست پایه پلتفرم. فروشنده می‌تواند سخاوتمندانه‌تر باشد ولی نمی‌تواند این حق را بردارد.',
    seedValue: null,
    min: 0,
    max: 365,
  },
  {
    key: 'market.shop.delivery_dispute_window_days',
    group: 'COMMERCE',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'مهلت اعتراض به تحویل (روز)',
    noteFa: 'تا پایان این مهلت، مبلغ زیرسفارش قابل تسویه نمی‌شود.',
    seedValue: null,
    min: 0,
    max: 365,
  },
  {
    key: 'market.shop.max_shipping_fee_toman',
    group: 'COMMERCE',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'سقف هزینه ارسال هر زیرسفارش',
    noteFa: 'کران عمومی که فروشنده نمی‌تواند از آن بالاتر برود. هزینه واقعی را خود فروشنده تعریف می‌کند.',
    seedValue: null,
  },
  {
    key: 'market.shop.max_free_shipping_threshold_toman',
    group: 'COMMERCE',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'سقف حد نصاب ارسال رایگان',
    noteFa: 'بالاترین عددی که فروشنده می‌تواند به‌عنوان حد نصاب ارسال رایگان اعلام کند.',
    seedValue: null,
  },
  {
    key: 'market.shop.promotion_stacking',
    group: 'COMMERCE',
    kind: 'JSON',
    source: 'OPERATIONAL_DATA',
    labelFa: 'قواعد هم‌زمانی تخفیف‌ها',
    noteFa:
      'یک شیء JSON که می‌گوید کدام نوع تخفیف با کدام یکی جمع می‌شود و اولویت اعمال چیست. تا ثبت، هیچ دو تخفیفی هم‌زمان اعمال نمی‌شود.',
    seedValue: null,
  },
  {
    key: 'market.shop.loyalty_points_per_1000_toman',
    group: 'COMMERCE',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'امتیاز خرید به ازای هر ۱۰۰۰ تومان',
    noteFa: 'امتیاز فقط پس از تکمیل سفارش و پایان مهلت مرجوعی ثبت می‌شود.',
    seedValue: null,
    min: 0,
    max: 10000,
  },
  {
    key: 'market.shop.loyalty_point_value_toman',
    group: 'COMMERCE',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'ارزش هر امتیاز خرید',
    noteFa: 'تا ثبت این مقدار، امتیاز جمع می‌شود ولی قابل خرج کردن نیست.',
    seedValue: null,
  },
  {
    key: 'market.shop.loyalty_expiry_days',
    group: 'COMMERCE',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'اعتبار امتیاز خرید (روز)',
    noteFa: 'خالی بودن یعنی سیاست انقضا هنوز تعیین نشده است، نه اینکه امتیاز بی‌نهایت می‌ماند.',
    seedValue: null,
    min: 1,
    max: 3650,
  },

  // ── Phase 3: settlement (PROMPT-002, DEC-0204) ────────────────────────
  {
    key: 'market.settlement.default_cadence',
    group: 'SETTLEMENT',
    kind: 'STRING',
    source: 'OPERATIONAL_DATA',
    labelFa: 'دوره پیش‌فرض تسویه',
    noteFa: 'مقدار WEEKLY یا MONTHLY. فروشنده می‌تواند دوره خودش را انتخاب کند و تغییر از دوره بعد اعمال می‌شود.',
    seedValue: null,
  },
  {
    key: 'market.settlement.hold_days_after_delivery',
    group: 'SETTLEMENT',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'نگه‌داشت مبلغ پس از تحویل (روز)',
    noteFa: 'مبلغ پس از تحویل و پایان این نگه‌داشت از «در انتظار» به «قابل تسویه» می‌رود. مبلغ مورد اختلاف هرگز تسویه نمی‌شود.',
    seedValue: null,
    min: 0,
    max: 365,
  },
  {
    key: 'market.settlement.minimum_payout_toman',
    group: 'SETTLEMENT',
    kind: 'MONEY_TOMAN',
    source: 'OPERATIONAL_DATA',
    labelFa: 'حداقل مبلغ قابل تسویه',
    noteFa: 'مانده کمتر از این مقدار به دوره بعد منتقل می‌شود.',
    seedValue: null,
  },
  {
    key: 'market.settlement.batch_cutoff_hour',
    group: 'SETTLEMENT',
    kind: 'INT',
    source: 'OPERATIONAL_DATA',
    labelFa: 'ساعت بسته‌شدن دسته تسویه',
    noteFa: 'ساعت شبانه‌روز (۰ تا ۲۳) که دسته تسویه آن دوره بسته می‌شود.',
    seedValue: null,
    min: 0,
    max: 23,
  },

  // ── Phase 3: kill switches (PROMPT-002, DEC-0204) ─────────────────────
  //
  // Every one starts closed, because nothing behind them is built yet and a
  // switch that reads «باز» over an unbuilt flow is a lie the rest of the phase
  // would inherit. Clearing one back to NOT_CONFIGURED also reads as closed.
  {
    key: 'market.flag.animal_market_enabled',
    group: 'MARKETPLACE_OPERATIONS',
    kind: 'BOOL',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'کلید کلی بازار فروش حیوان',
    noteFa: 'بستن این کلید همه مسیرهای بازار حیوان را می‌بندد؛ آگهی‌های ثبت‌شده حذف نمی‌شوند.',
    seedValue: false,
  },
  {
    key: 'market.flag.animal_listing_creation_enabled',
    group: 'MARKETPLACE_OPERATIONS',
    kind: 'BOOL',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'کلید ثبت آگهی تازه حیوان',
    noteFa: 'بستن این کلید فقط جلوی ثبت آگهی تازه را می‌گیرد؛ معامله‌های در جریان ادامه می‌یابند.',
    seedValue: false,
  },
  {
    key: 'market.flag.commerce_checkout_enabled',
    group: 'MARKETPLACE_OPERATIONS',
    kind: 'BOOL',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'کلید پرداخت سبد فروشگاه',
    noteFa: 'بستن این کلید جلوی شروع پرداخت تازه را می‌گیرد؛ سفارش‌های پرداخت‌شده دست‌نخورده می‌مانند.',
    seedValue: false,
  },
  {
    key: 'market.flag.seller_onboarding_enabled',
    group: 'MARKETPLACE_OPERATIONS',
    kind: 'BOOL',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'کلید ثبت‌نام فروشنده کالا',
    noteFa: 'بستن این کلید جلوی درخواست تازه فروشندگی را می‌گیرد؛ فروشندگان فعال ادامه می‌دهند.',
    seedValue: false,
  },
  {
    key: 'market.flag.payout_enabled',
    group: 'MARKETPLACE_OPERATIONS',
    kind: 'BOOL',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'کلید تسویه با فروشندگان',
    noteFa: 'بستن این کلید اجرای دسته تسویه را متوقف می‌کند؛ مانده‌ها محفوظ می‌مانند.',
    seedValue: false,
  },
  {
    key: 'market.flag.promotion_enabled',
    group: 'MARKETPLACE_OPERATIONS',
    kind: 'BOOL',
    source: 'TECHNICAL_DEFAULT',
    labelFa: 'کلید تخفیف‌ها و کمپین‌ها',
    noteFa: 'بستن این کلید اعمال تخفیف تازه را متوقف می‌کند؛ تخفیف اعمال‌شده روی سفارش ثبت‌شده بازنویسی نمی‌شود.',
    seedValue: false,
  },
];

export const SETTING_BY_KEY: ReadonlyMap<string, SettingDefinition> = new Map(
  SETTING_DEFINITIONS.map((d) => [d.key, d]),
);

export const SETTING_KEYS = SETTING_DEFINITIONS.map((d) => d.key);
